/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RequestDeviceSnmpProtocolAttributes {
    #[serde(rename = "snmp_v1", skip_serializing_if = "Option::is_none")]
    pub snmp_v1: Option<Box<crate::models::RequestDeviceSnmpProtocolAttributesSnmpV1>>,
    #[serde(rename = "snmp_v2c", skip_serializing_if = "Option::is_none")]
    pub snmp_v2c: Option<Box<crate::models::RequestDeviceSnmpProtocolAttributesSnmpV1>>,
    #[serde(rename = "snmp_v3", skip_serializing_if = "Option::is_none")]
    pub snmp_v3: Option<Box<crate::models::RequestDeviceSnmpProtocolAttributesSnmpV3>>,
}

impl RequestDeviceSnmpProtocolAttributes {
    pub fn new() -> RequestDeviceSnmpProtocolAttributes {
        RequestDeviceSnmpProtocolAttributes {
            snmp_v1: None,
            snmp_v2c: None,
            snmp_v3: None,
        }
    }
}
