/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RequestDeviceAgent : An agent as a response body.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RequestDeviceAgent {
    /// The name of this agent.
    #[serde(rename = "id")]
    pub id: String,
}

impl RequestDeviceAgent {
    /// An agent as a response body.
    pub fn new(id: String) -> RequestDeviceAgent {
        RequestDeviceAgent {
            id,
        }
    }
}


