/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RequestDeviceSnmpProtocolAttributesSnmpV1 {
    #[serde(rename = "community", skip_serializing_if = "Option::is_none")]
    pub community: Option<String>,
}

impl RequestDeviceSnmpProtocolAttributesSnmpV1 {
    pub fn new() -> RequestDeviceSnmpProtocolAttributesSnmpV1 {
        RequestDeviceSnmpProtocolAttributesSnmpV1 { community: None }
    }
}
