/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ResponseDevices : An managed device and the number of all items as a response body.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResponseDevices {
    /// The list of devices
    #[serde(rename = "devices")]
    pub devices: Vec<crate::models::ResponseDevicesDevicesInner>,
    /// The number of all items
    #[serde(rename = "num_items")]
    pub num_items: i64,
}

impl ResponseDevices {
    /// An managed device and the number of all items as a response body.
    pub fn new(devices: Vec<crate::models::ResponseDevicesDevicesInner>, num_items: i64) -> ResponseDevices {
        ResponseDevices {
            devices,
            num_items,
        }
    }
}


