/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ResponseAgents : List of agents and the number of all items as a response body.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResponseAgents {
    /// List of agents
    #[serde(rename = "agents")]
    pub agents: Vec<crate::models::ResponseAgentsAgentsInner>,
    /// The number of all items
    #[serde(rename = "num_items")]
    pub num_items: i64,
}

impl ResponseAgents {
    /// List of agents and the number of all items as a response body.
    pub fn new(agents: Vec<crate::models::ResponseAgentsAgentsInner>, num_items: i64) -> ResponseAgents {
        ResponseAgents {
            agents,
            num_items,
        }
    }
}


