/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ResponseAgent : An agent as a response body.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResponseAgent {
    /// The unique identifier of this agent.
    #[serde(rename = "id")]
    pub id: String,
    /// The name of this agent.
    #[serde(rename = "name")]
    pub name: String,
}

impl ResponseAgent {
    /// An agent as a response body.
    pub fn new(id: String, name: String) -> ResponseAgent {
        ResponseAgent {
            id,
            name,
        }
    }
}


