/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ResponseDevices : An managed device and the number of all items as a response body.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResponseDevices {
    /// The number of all items
    #[serde(rename = "count")]
    pub count: i64,
    /// The list of devices
    #[serde(rename = "items")]
    pub items: Vec<crate::models::ResponseDevicesItemsInner>,
}

impl ResponseDevices {
    /// An managed device and the number of all items as a response body.
    pub fn new(count: i64, items: Vec<crate::models::ResponseDevicesItemsInner>) -> ResponseDevices {
        ResponseDevices {
            count,
            items,
        }
    }
}


