/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ResponseAgents : List of agents and the number of all items as a response body.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResponseAgents {
    /// The number of all items
    #[serde(rename = "count")]
    pub count: i64,
    /// List of agents
    #[serde(rename = "items")]
    pub items: Vec<crate::models::ResponseAgentsItemsInner>,
}

impl ResponseAgents {
    /// List of agents and the number of all items as a response body.
    pub fn new(count: i64, items: Vec<crate::models::ResponseAgentsItemsInner>) -> ResponseAgents {
        ResponseAgents {
            count,
            items,
        }
    }
}


