// generated by `sqlx migrate build-script`
fn main() -> std::io::Result<()> {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");
    
    let man_dir = std::path::PathBuf::from(std::env::var_os("MAN_DIR").ok_or_else(|| std::io::ErrorKind::NotFound)?);

    let cmd = clap::Command::new("mybin")
        .arg(clap::arg!(-n --name <NAME>))
        .arg(clap::arg!(-c --count <NUM>));

    let man = clap_mangen::Man::new(cmd);
    let mut buffer: Vec<u8> = Default::default();
    man.render(&mut buffer)?;

    std::fs::write(man_dir.join("mybin.1"), buffer)?;

    Ok(())
}
