version: '3.9'
services:
  snmp-sim:
    image: fhorvath80/snmp-sim-rust
    build:
      context: .
    ports:
      - 8080:8080/tcp
      - 30160-30200:30160-30200/udp
    restart: unless-stopped
    logging:
      options:
        max-size: "100k"
        max-file: "3"
    volumes:
      - ${PWD}/snmp-sim.db:/root/.snmp-sim/snmp-sim.db
