extend= [
  { path = "coverage_grcov.makefile.toml" }
]

[env]
PROJ_NAME = "snmp-sim"

[config]
default_to_workspace = false

[tasks.audit]
ignore_errors = true

[tasks.install-openapi]
script = '''
sudo apt update && sudo apt install -y python3 python3-pip protobuf-compiler openjdk-11-jre-headless curl maven jq
pip3 install yq
mkdir -p ~/bin/openapitools
curl https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/bin/utils/openapi-generator-cli.sh > ~/bin/openapitools/openapi-generator
chmod u+x ~/bin/openapitools/openapi-generator
export PATH="$PATH:~/bin/openapitools"
'''

[tasks.format]
description = "Runs the cargo rustfmt plugin."
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.lint]
description = "Runs the cargo clippy plugin."
script = ['''
#!/usr/bin/env bash -eux
cargo clippy --workspace --all-targets --all-features -- -D warnings
''']

[tasks.coverage]
alias="coverage_grcov"

[tasks.install-llvm-tools]
category = "Tools"
description = "Installs llvm-tools-preview rustup component."
install_crate = { rustup_component_name = "llvm-tools-preview" }

[tasks.install-deps]
dependencies = [ "install-llvm-tools" ]
