[package]
name = "snmp-data-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
strum = "*"
strum_macros = "*"

[features]
default = ["snmpdata"]
snmpdata = ["property"]
property = ["line"]
line = []
