name: CI
on: [push, pull_request]
env:
  CLICOLOR_FORCE: 1
jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust: [1.60]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --force cargo-make
      - name: Run CI
        if: matrix.rust == 'stable' || matrix.rust == 'beta'
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --target-dir target/ci -- make ci-flow
      - name: Run CI (Allow Failures)
        if: matrix.rust == 'nightly'
        continue-on-error: true
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --target-dir target/ci -- make ci-flow
      - name: Run CI (Minimal Supported Rust Version)
        if: matrix.rust != 'stable' && matrix.rust != 'beta' && matrix.rust != 'nightly' && matrix.os == 'ubuntu-latest'
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: ci-flow
