name: rustfmt and clippy
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
  workflow_dispatch:

env:
  CLICOLOR_FORCE: 1
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: all

jobs:
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: clippy
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all -- -D clippy::all
        continue-on-error: true

  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          toolchain: ${{ matrix.rust }}
          command: fmt
          args: --all -- --check
